config/routes.rb
Loja::Application.routes.draw do

  root :to => 'produtos#index'
  resources :produtos

  resource :usuario
  resource :session

  resources :itens do
    collection do
      put :atualizar_quantidades
    end
  end

  resources :linguas

  namespace :admin do
    resources :produtos
    resources :categorias
  end

end

app/models/categoria.rb
class Categoria < ActiveRecord::Base

  validates_presence_of    :nome
  validates_uniqueness_of  :nome, :allow_blank => true
  validates_length_of      :nome, :minimum => 4

  has_many :produtos

end

app/models/item.rb
class Item < ActiveRecord::Base

  belongs_to :pedido
  belongs_to :produto

  validates_presence_of     :pedido_id, :produto_id, :quantidade
  validates_numericality_of :quantidade, :only_integer => true,
                            :greater_than => 0

  def incrementar_quantidade( quantidade )
    self.quantidade += quantidade.to_i
  end

  def nome
    self.produto.nome
  end

  def preco_unitario
    self.produto.preco
  end

  def preco_total
    self.preco_unitario * self.quantidade
  end

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base

  has_many :itens, :dependent => :destroy
  accepts_nested_attributes_for :itens
  has_many :produtos, :through => :itens

  before_validation :remover_itens_invalidos

  def adicionar_produto( produto, quantidade )

    if item = self.itens.detect { |item| item.produto == produto }
      item.incrementar_quantidade ( quantidade )
      item.save
    else
      self.itens.create(
          :produto_id => produto.id,
          :quantidade => quantidade
      )
    end

  end

  def preco_total
    self.itens.inject( 0 ) do |acumulado, item|
      acumulado + item.preco_total
    end
  end

  def remover_itens_invalidos
    itens_invalidos = self.itens.find_all do |item|
      item.invalid?
    end
    self.itens.delete( * itens_invalidos )
  end

end

app/models/produto.rb
class Produto < ActiveRecord::Base

  validates_presence_of :nome, :preco, :descricao
  validates_length_of :nome, :minimum =>  4
  validates_numericality_of :preco, :greater_than => 0, :allow_blank => true

  belongs_to :categoria

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  attr_accessor             :senha, :termos_e_condicoes

  before_validation :calcular_senha

  validates_presence_of     :nome, :email

  validates_uniqueness_of   :email

  validates_acceptance_of   :termos_e_condicoes, :if => :new_record?

  validates_presence_of     :senha_em_hash, :if => :senha_necessaria?

  validates_confirmation_of :senha, :if => :senha_necessaria?

  validates_length_of       :senha, :within => 4..40, :if => :senha_necessaria?

  def senha_necessaria?

    !self.senha.blank? || self.senha_em_hash.blank?

  end

  def calcular_senha
    return if self.senha.blank?

    if self.salt.blank?
      hash = "#{Time.now.to_s}-#{self.email}-#{rand(Time.now.to_i)})"
      self.salt = Digest::SHA1.hexdigest( hash )
    end

    self.senha_em_hash = Usuario.hashear_senha( self.senha, self.salt )

  end

  def self.hashear_senha( senha, salt )
    Digest::SHA1.hexdigest( "--#{senha}--#{salt}" )
  end

  def self.autenticar( email, senha )

    usuario = Usuario.where( :email => email ).first

    if usuario && usuario.senha_em_hash == hashear_senha( senha, usuario.salt )
      usuario
    else
      nil
    end

  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  layout 'administracao'

end

app/controllers/admin/categorias_controller.rb
class Admin::CategoriasController < Admin::BaseController

  include ControllerGeneratorHelper

  gerar_controller Categoria

end

app/controllers/admin/produtos_controller.rb
class Admin::ProdutosController < Admin::BaseController

  include ControllerGeneratorHelper

  gerar_controller Produto



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include AutorizacaoControllerHelper

  helper_method :pedido_atual

  before_filter :selecionar_lingua

  protected

  def selecionar_lingua

    I18n.locale = session[:lingua] ||= 'pt-BR'

  end

  def pedido_atual
    @pedido_atual ||= if !session[:pedido_id].blank?
      Pedido.find( session[:pedido_id] )
    else
      Pedido.new
    end
  end

  def carregar_pagina
    @page = params[:page] || 1
    @per_page = params[:per_page] || 10
  end

  def paginate ( scope )
    carregar_pagina
    scope.paginate( :per_page => @per_page, :page => @page )
  end

end

app/controllers/itens_controller.rb
class ItensController < ApplicationController

  def index

  end

  def atualizar_quantidades

    pedido_atual.update_attributes(params[:pedido])

    respond_to do |format|
      format.html do
        flash[:success] = 'Quantiddades atualizadas com sucesso'
        redirect_to itens_url
      end
    end
  end

  def create

    if pedido_atual.new_record?
      pedido_atual.save
      session[:pedido_id] = pedido_atual.id
    end

    produto = Produto.find( params[:produto_id] )

    pedido_atual.adicionar_produto( produto, params[:quantidade] )


    respond_to do |format|
      format.html do
        flash[:success] = 'Produto adicionado com sucesso'
        redirect_to produto_url( produto )
      end
    end

  end

end

app/controllers/linguas_controller.rb
class LinguasController < ApplicationController

  def index
    session[:lingua] = params[:lang]
    redirect_to :back   # prestar atenção para caso de POST ou PUT. Testar antes - implementar
  end

end

app/controllers/produtos_controller.rb
# encoding: utf-8
class ProdutosController < ApplicationController

  def index
    @produtos = Produto.all
    flash.now[:success] = 'Isso é um flash com sucesso'

    respond_to do | format |
      format.html
      format.json { render :json => @produtos }
      format.xml  { render :xml  => @produtos }
    end
  end

  def show
    @produto = Produto.find( params[:id] )
  end

end

app/controllers/sessions_controller.rb
# encoding: utf-8
class SessionsController < ApplicationController

  def new

    @usuario = Usuario.new
    render :action => 'new'

  end

  def create

    @usuario = Usuario.autenticar(
        params[:usuario][:email],
        params[:usuario][:senha]
    )

    if @usuario
      self.usuario_atual = @usuario
      flash[:success] = 'Bem-vindo à Loja'
      redirect_to produtos_url
    else
      flash.now[:error] = "Não foi possível fazer o seu login com os dados enviados"
      new
    end

  end

  def destroy
    reset_session
    flash[:success] = "Você saiu com sucesso da aplicação"
    redirect_to produtos_url
  end

end

app/controllers/usuarios_controller.rb
# encoding: utf-8
class UsuariosController < ApplicationController

  def new
    @usuario = Usuario.new
  end

  def create
    @usuario = Usuario.new( params[:usuario] )
    if @usuario.save
      self.usuario_atual = @usuario
      flash[:success] = 'Seu usuário foi criado com sucesso'
      redirect_to produtos_url
    else
      render :action => 'new'
    end

  end

end

app/helpers/admin/produtos_helper.rb
module Admin::ProdutosHelper

  def admin_form_for( record, &block )

    result = if record.new_record?
               [ send( "admin_#{record.class.name.underscore.pluralize}_url"), :post ]
             else
               [ send( "admin_#{record.class.name.underscore}_url", record), :put ]
             end

    form_for( record,
              :url => result.first,
              :method => result.last,
              :builder =>  BootstrapFormBuilder,
              &block )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

  def t( key, options = {} )
    I18n.translate( key, options )
  end

end

app/helpers/bootstrap_form_builder.rb
class BootstrapFormBuilder < ActionView::Base::FormBuilder

  [ :text_field, :text_area, :password_field, :check_box, :select ].each do |method|

    define_method( method ) do |name, *args|
      wrap( name, super(name, *args))
    end

  end


  def wrap(name, content)
    classes = [ 'clearfix']
    error_message = ''
    unless self.object.errors[ name ].blank?
      classes << 'error'
      messages = self.object.errors[ name ].to_sentence
      error_message = %Q!
        <span class="help-inline">#{messages}</span>
    !

    end

    markup = %Q!
      <div class="#{classes.join( ' ' )}">
        <label>#{self.object.class.human_attribute_name( name )}</label>
        <div class="input">
          #{content}
          #{error_message}
        </div>
      </div>
    !

    markup.html_safe
  end

end

app/views/admin/categorias/index.html.haml
%h1 Lista de categorias

%p= link_to 'Nova categoria', new_admin_categoria_url

= will_paginate @categorias

%table
  %thead
    %tr
      %td Nome
  %tbody
    - @categorias.each do |categoria|
      %tr
        %td= link_to categoria.nome, edit_admin_categoria_url(categoria)

= will_paginate @categorias

app/views/admin/categorias/new.html.haml
%h1 Criar/Atualizar Categoria

= admin_form_for( @categoria ) do |f|

  = f.text_field :nome
  = f.text_area :descricao

  .actions
    %p= f.submit 'Enviar', :class => 'btn primary'

app/views/admin/produtos/index.html.haml
%h1 Produtos

%p= link_to 'Novo Produto', new_admin_produto_url

= will_paginate @produtos

%table
  %thead
    %tr
      %th Nome
      %th Categoria
      %th Preço
  %tbody
    - @produtos.each do |produto|
      %tr
        %td= produto.nome
        %td
          - if produto.categoria
            = produto.categoria.nome
          - else
            == -
        %td= number_to_currency produto.preco
        %td= link_to 'Editor', edit_admin_produto_url( produto )

= will_paginate @produtos

app/views/admin/produtos/new.html.haml
%h1
  = t( 'formularios.criar_atualizar', :tipo => Produto.model_name.human )

= admin_form_for( @produto ) do |f|

  = f.text_field :nome
  = f.text_field :preco
  = f.select     :categoria_id, Categoria.all.map { |c| [c.nome, c.id] }, :include_blank => "Escolha..."
  = f.text_area  :descricao

  .actions
    %p= f.submit 'Enviar', :class => 'btn primary'

app/views/compartilhados/_mostrar_flash.html.haml
- [:success, :warning, :error, :info].each do |key|
  - unless flash[key].blank?
    %div{ :class => "alert-message #{key}" }
      = link_to 'x', "javascript:void(0)", :class => "close"
      %p= flash[key]

app/views/itens/_item.html.haml
%tr
  %td= item.nome
  %td
    = text_field_tag 'pedido[itens_attributes][][quantidade]', item.quantidade
    = hidden_field_tag 'pedido[itens_attributes][][id]', item.id
    = submit_tag 'Atualizar', :class => 'btn'
  %td= number_to_currency item.preco_unitario
  %td= number_to_currency item.preco_total

app/views/itens/index.html.haml
%h1 Meus Produtos

= form_tag atualizar_quantidades_itens_url, :method => :put do
  %table.zebra-striped#pedido
    %thead
      %tr
        %th Nome
        %th Quantidade
        %th Preço Unitário
        %th Preço Total
    %tbody
      - pedido_atual.itens.each do |item|
        = render 'item', :item => item

    %tfoot
      %tr
        %td{ :colspan => 2 }
        %td Preço Total
        %td= number_to_currency pedido_atual.preco_total

app/views/layouts/_past_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="topbar-wrapper" style="z-index: 5;">
  <div class="topbar">
    <div class="topbar-inner">
      <div class="container">
        <h3> <%= link_to 'Minha Loja', root_url %> </h3>
        <% unless pedido_atual.itens.blank? %>
            <ul class="nav secondary-nav">
              <li>
                <%= link_to 'Veja o seu carrinho', itens_path %>
              </li>
            </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <% [:success, :warning, :error, :info].each do |key| %>

    <% unless flash[key].blank? %>
      <div class="alert-message <%= key %>">
         <a class="close" href="#">x</a>
         <p><%= flash[key] %></p>
       </div>
    <% end %>

  <% end %>

  <%= yield %>

</div>



</body>
</html>

app/views/layouts/administracao.html.haml
!!! 5
%html
  %head
    %title Loja - Administração
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .topbar-wrapper{ :style => 'z-index: 5;' }
      .topbar{ :'data-dropdown' => 'dropdown' }
        .topbar-inner
          .container
            %h3= link_to 'Administração', admin_produtos_url
            %ul.nav
              %li.dropdown
                = link_to 'Línguas', 'javascript:void(0)', :class => 'dropdown-toggle'
                %ul.dropdown-menu
                  %li= link_to 'Português', linguas_path( :lang => 'pt-BR' )
                  %li= link_to 'English', linguas_path( :lang => 'en' )

    .container
      = render 'compartilhados/mostrar_flash'
      = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loja</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="topbar-wrapper" style="z-index: 5;">
  <div class="topbar">
    <div class="topbar-inner">
      <div class="container">
        <h3> <%= link_to 'Minha Loja', root_url %> </h3>
        <% unless pedido_atual.itens.blank? %>
            <ul class="nav secondary-nav">
              <li>
                <%= link_to 'Veja o seu carrinho', itens_path %>
              </li>
            </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">

  <% [:success, :warning, :error, :info].each do |key| %>

    <% unless flash[key].blank? %>
      <div class="alert-message <%= key %>">
         <a class="close" href="#">x</a>
         <p><%= flash[key] %></p>
       </div>
    <% end %>

  <% end %>

  <%= yield %>

</div>



</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Loja
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .topbar-wrapper{ :style => 'z-index: 5;' }
      .topbar
        .topbar-inner
          .container
            %h3= link_to "Minha Loja", root_url
            %ul.nav.secondary-nav
              - if logged_in?
                %li== Seja bem-vindo #{usuario_atual.nome}
                %li= link_to 'Logoff', session_url, :method => :delete, :confirm => "Tem certeza?"
              - else
                %li= link_to 'Crie a sua conta', new_usuario_url
                %li= link_to 'Faça login', new_session_url
              - unless pedido_atual.itens.blank?
                %li= link_to 'Veja o seu carrinho', itens_path

    .container
      = render 'compartilhados/mostrar_flash'
      = yield

app/views/produtos/index.html.erb
<h1><%= t( 'produtos.index.titulo') %></h1>

<table class="zebra-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Preço</th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
    <tr>
      <td><%= link_to produto.nome, produto_url(produto) %></td>
      <td><%= number_to_currency( produto.preco) %></td>
      <td>
        <%= form_tag itens_url do %>
          <%= hidden_field_tag :produto_id, produto.id %>
          <%= text_field_tag :quantidade, 1 %>
          <%= submit_tag 'Adicionar', :class => 'btn primary' %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/usuarios/new.html.haml
%h2 Crie sua conta
= form_for( @usuario, :url => usuario_url, :builder => BootstrapFormBuilder ) do |f|
  %fieldset
    %legend Crie sua conta
    = f.text_field :nome
    = f.text_field :email
    = f.password_field :senha
    = f.password_field :senha_confirmation
    = f.check_box :termos_e_condicoes
    .actions
      = f.submit( 'Criar', :class => 'btn primary' )